#!/bin/bash
TAG_NAME="${TRAVIS_TAG:-latest}"
docker tag $IMAGE_NAME $IMAGE_NAME_REMOTE:$TAG_NAME
echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_USERNAME --password-stdin
docker push $IMAGE_NAME_REMOTE:$TAG_NAME