name: Continuous Integration

on:
  push:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hepdata-converter-ws
    - name: Deploy
      if: contains(github.ref, 'main') || github.event_name == 'release'
      env:
        CI_TAG: ${{ github.event.release.tag_name }}
        IMAGE_NAME: hepdata-converter-ws
        IMAGE_NAME_REMOTE: hepdata/hepdata-converter-ws
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        bash docker_push
